name: flutter_mobx
description:
  Flutter integration for MobX. It provides the Observer widget that automatically rebuilds
  when the tracked observables change.
version: 0.3.0+1
authors:
  - Joni Katajamäki <joni.katajamaki@gmail.com>
  - Pavan Podila <pavan@pixelingene.com>

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  mobx: ^0.3.5

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  mobx_codegen: ^0.3.3+1

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

